services:

  JWT:
    image: jwt-image:latest
    container_name: jwt-container
    ports:
      - 5000:4000
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=localdatabase
      - POSTGRES_PORT=5432
    networks:
      - default
    links:
      - postgreSQL-DB

  Migration:
    image: migration-image:latest
    container_name: migration-contaier
    ports:
      - 5001:3000
    environment:
      - DB_HOST=localdatabase
      - DB_URI=postgresql://postgres:1@localdatabase:5432/testdb
    networks:
      - default
    links:
      - postgreSQL-DB

  postgreSQL-DB:
    image: postgres:alpine3.18
    container_name: localdatabase
    expose:
      - 5432
    ports:
      - 5002:5432
    restart: unless-stopped
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_PASSWORD=1
      - POSTGRES_USER=postgres


  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    volumes:
       - ./servers.json:/pgadmin4/servers.json
       - ./pgpass:/pgpass
    links:
      - postgreSQL-DB

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus/
    container_name: prometheus
    hostname: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 5003:9090
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    networks:
      - default
    depends_on:
      - exporter
# testzelyakov@gmail.com
# ldlanpviqxzjfwiz
  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    restart: always
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    deploy:
      mode: global
    networks:
      - default

  exporter:
    image: wrouesnel/postgres_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:1@localdatabase:5432/testdb?sslmode=disable"
      PG_EXPORTER_EXTEND_QUERY_PATH: "/var/query.yml"
    ports:
      - "9187:9187"
    restart: unless-stopped  
    volumes:
       - ./postgres_exporter.yml
       - ./:/var
    networks:
      - default
    depends_on:
      - postgreSQL-DB

  grafana:
    image: grafana/grafana
    user: root
    depends_on:
      - prometheus
    ports:
      - 5005:3000
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    networks:
      - default
    links:
      - "Migration"

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.24.0.0/16