groups:
- name: 'changes'
  rules:
  - alert: AddNewUser
    expr: changes(pg_number_of_users_count{server="localdatabase:5432"}[31s]) != 0
    for: 5s
    labels:
      severity: 'adds'
    annotations:
      summary: "New user was added"